import { OrbitControls, Text } from '@react-three/drei'
import * as THREE from 'three'
import { site } from '../data/site'
import ThirdPersonController from './ThirdPersonController'
import ArchitecturalProjectLayer from './ArchitecturalProjectLayer'
import RoofLayer from './RoofLayer'

const WORKSPACE_SIZE=56,HALF=28,ROAD_WIDTH=5.97,SIDEWALK_WIDTH=1.01,NEIGHBOR_WIDTH=11,GREEN_DEPTH=5.5,CONTEXT_HALF_WIDTH=site.boundaries.front/2+NEIGHBOR_WIDTH
function CardinalMarker({label,position}){return <Text position={position} rotation={[-Math.PI/2,0,0]} fontSize={.72} color="#0f172a">{label}</Text>}
function ConstructionWorkspace(){return <group><mesh position={[0,-.14,0]} receiveShadow><boxGeometry args={[56,.08,56]}/><meshStandardMaterial color="#f8fafc" roughness={1}/></mesh><gridHelper args={[56,56,'#94a3b8','#d7dde5']} position={[0,-.09,0]}/><CardinalMarker label="N" position={[0,.08,-HALF+.8]}/><CardinalMarker label="S" position={[0,.08,HALF-.8]}/><CardinalMarker label="L" position={[HALF-.8,.08,0]}/><CardinalMarker label="O" position={[-HALF+.8,.08,0]}/></group>}
function shapeFrom(points){const s=new THREE.Shape();points.forEach(([x,z],i)=>i?s.lineTo(x,-z):s.moveTo(x,-z));s.closePath();return s}
function Area({points,color,border='#66705b'}){const s=shapeFrom(points);return <group><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><shapeGeometry args={[s]}/><meshStandardMaterial color={color} roughness={1} side={THREE.DoubleSide}/></mesh><lineSegments rotation={[-Math.PI/2,0,0]} position={[0,.025,0]}><edgesGeometry args={[new THREE.ShapeGeometry(s)]}/><lineBasicMaterial color={border}/></lineSegments></group>}
function GroundText({children,x,z,size=.42,rotation=0,color='#334155'}){return <Text position={[x,.07,z]} rotation={[-Math.PI/2,0,rotation]} fontSize={size} color={color} anchorX="center" anchorY="middle">{children}</Text>}
function Tree({x,z,scale=1}){return <group position={[x,0,z]} scale={scale}><mesh position={[0,.62,0]}><cylinderGeometry args={[.11,.17,1.24,8]}/><meshStandardMaterial color="#72583d"/></mesh><mesh position={[0,1.55,0]} castShadow><sphereGeometry args={[.7,12,10]}/><meshStandardMaterial color="#47713c"/></mesh></group>}
function StreetLayer(){const h=CONTEXT_HALF_WIDTH,a=SIDEWALK_WIDTH,b=a+ROAD_WIDTH;return <group><Area points={[[-h,0],[h,0],[h,a],[-h,a]]} color="#dedfdb"/><Area points={[[-h,a],[h,a],[h,b],[-h,b]]} color="#70757c"/><GroundText x={0} z={a+ROAD_WIDTH*.42} size={.58} color="#e5e7eb">RUA I</GroundText><GroundText x={-h+1.15} z={a/2} size={.27}>1,01 m</GroundText><GroundText x={h-1.1} z={a+ROAD_WIDTH/2} size={.3} rotation={Math.PI/2} color="#e5e7eb">5,97 m</GroundText></group>}
function rearBoundary(){const h=site.boundaries.front/2,l=site.boundaries.leftOnDrawing,r=site.boundaries.rightOnDrawing,s=(l-r)/(2*h);return x=>-l+(x+h)*s}
function LotsLayer(){const h=site.boundaries.front/2,lx=-h-NEIGHBOR_WIDTH,rx=h+NEIGHBOR_WIDTH,l=site.boundaries.leftOnDrawing,r=site.boundaries.rightOnDrawing,rz=rearBoundary();return <group><Area points={[[lx,0],[-h,0],[-h,-l],[lx,rz(lx)]]} color="#d8d8c8"/><Area points={[[-h,0],[h,0],[h,-r],[-h,-l]]} color="#9ab779" border="#365314"/><Area points={[[h,0],[rx,0],[rx,rz(rx)],[h,-r]]} color="#d8d8c8"/><GroundText x={lx+NEIGHBOR_WIDTH/2} z={rz(lx+NEIGHBOR_WIDTH/2)/2}>LOTE 05</GroundText><GroundText x={0} z={rz(0)/2} color="#294b24">LOTE 04 · QUADRA 07{`\n`}396,55 m²</GroundText><GroundText x={h+NEIGHBOR_WIDTH/2} z={rz(h+NEIGHBOR_WIDTH/2)/2}>LOTE 03</GroundText><GroundText x={0} z={-.55} size={.31}>17,84 m</GroundText><GroundText x={0} z={rz(0)+.62} size={.31}>17,92 m</GroundText><GroundText x={-h+.5} z={-l/2} size={.3} rotation={Math.PI/2}>23,07 m</GroundText><GroundText x={h-.5} z={-r/2} size={.3} rotation={Math.PI/2}>21,41 m</GroundText></group>}
function GreenLayer(){const rz=rearBoundary(),lx=-CONTEXT_HALF_WIDTH,rx=CONTEXT_HALF_WIDTH,nl=rz(lx),nr=rz(rx);return <group><Area points={[[lx,nl],[rx,nr],[rx,nr-GREEN_DEPTH],[lx,nl-GREEN_DEPTH]]} color="#a8bc8e"/><GroundText x={0} z={rz(0)-GREEN_DEPTH/2} color="#365314">ÁREA VERDE DO CONDOMÍNIO</GroundText>{[-15,-10,-5,0,5,10,15].map((x,i)=><Tree key={x} x={x} z={rz(x)-3+(i%2?.55:-.35)}/>)}</group>}
export default function HouseScene({viewMode,layers,materials,roofConfig}){const top=viewMode==='top',walk=viewMode==='walk';return <><color attach="background" args={['#e7ebef']}/><ambientLight intensity={1.35}/><directionalLight position={[10,18,14]} intensity={1.8} castShadow/>{layers.workspace&&<ConstructionWorkspace/>}{layers.green&&<GreenLayer/>}{layers.lots&&<LotsLayer/>}{layers.street&&<StreetLayer/>}{layers.architecture&&<ArchitecturalProjectLayer materials={materials}/>} {layers.roof&&<RoofLayer config={roofConfig}/>} {walk?<ThirdPersonController/>:<OrbitControls makeDefault enableDamping target={[0,0,-8]} minDistance={8} maxDistance={80} minPolarAngle={top?.01:.12} maxPolarAngle={top?.45:Math.PI/2.04} touches={{ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_ROTATE}}/>}</>}
