import { Canvas } from '@react-three/fiber'
import { Suspense,useState } from 'react'
import HouseScene from './components/HouseScene'
import MobileWalkControls from './components/MobileWalkControls'
import LayersMenu from './components/LayersMenu'
import MaterialsMenu from './components/MaterialsMenu'
import RoofMenu from './components/RoofMenu'
import { DEFAULT_MATERIAL_SELECTION } from './materials/materialPresets'
import { DEFAULT_ROOF_CONFIG } from './roof/roofPresets'

const INITIAL_LAYERS={workspace:true,street:true,lots:true,green:true,architecture:true,roof:true}
export default function App(){const[viewMode,setViewMode]=useState('perspective'),[layers,setLayers]=useState(INITIAL_LAYERS),[materials,setMaterials]=useState(DEFAULT_MATERIAL_SELECTION),[roofConfig,setRoofConfig]=useState(DEFAULT_ROOF_CONFIG);const toggleLayer=key=>setLayers(c=>({...c,[key]:!c[key]})),changeMaterial=(category,preset)=>setMaterials(c=>({...c,[category]:preset})),changeRoof=(key,value)=>setRoofConfig(c=>({...c,[key]:value}));const camera=viewMode==='top'?{position:[0,38,.01],fov:42}:viewMode==='walk'?{position:[0,3.2,8],fov:55}:{position:[0,10.5,22],fov:46};return <main className="relative h-dvh w-screen overflow-hidden bg-slate-900"><header className="pointer-events-none absolute left-0 right-0 top-0 z-20 flex items-start justify-between gap-3 p-3 md:p-5"><div className="pointer-events-auto max-w-[62vw] rounded-2xl border border-white/50 bg-white/90 px-4 py-3 shadow-xl backdrop-blur"><div className="text-xs font-medium uppercase tracking-[.18em] text-slate-500">Workspace arquitetônico</div><h1 className="text-lg font-semibold">Residence 3D Viewer</h1></div><div className="pointer-events-auto flex rounded-xl bg-slate-950/80 p-1">{[['perspective','3D'],['top','Planta'],['walk','Passeio']].map(([m,l])=><button key={m} onClick={()=>setViewMode(m)} className={`rounded-lg px-3 py-2 text-xs ${viewMode===m?'bg-white text-slate-900':'text-slate-300'}`}>{l}</button>)}</div></header><Canvas key={viewMode} shadows dpr={[1,1.75]} camera={camera}><Suspense fallback={null}><HouseScene viewMode={viewMode} layers={layers} materials={materials} roofConfig={roofConfig}/></Suspense></Canvas><RoofMenu config={roofConfig} onChange={changeRoof}/><MaterialsMenu materials={materials} onChange={changeMaterial}/><LayersMenu layers={layers} onToggle={toggleLayer}/>{viewMode==='walk'&&<MobileWalkControls/>}</main>}
